name = "makePackage"
uuid = "cbaa3187-80c3-4be7-a499-4fbf6e666fdf"
authors = ["khintz"]
version = "0.1.0"

[deps]
PkgTemplates = "14b8a8f1-9102-5b29-a752-f990bacb7fe1"

[compat]
PkgTemplates = "0.7"
julia = "1.5.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
